#
//  ci.yml
//  Xcodetest
//
//  Created by Lasitha Atapattu on 2025-05-04.
//

name: C/C++ CI

on:
  push:
    branches: [ "main", "developer" ]
  pull_request:
    branches: [ "main", "developer" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up CMake
      run: sudo apt-get update && sudo apt-get install -y cmake

    - name: Create build directory
      run: mkdir build

    - name: Configure
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build

